name: Bug Report
description: Report an issue
labels: [bug]
body:

  - type: checkboxes
    attributes:
      label: "Please search first"
      options:
        - label: "I have searched and there are no duplicates"
          required: true
          
  - type: input
    id: SpamBlocker-version
    attributes:
      label: SpamBlocker version
      description: |
        You can find the version in the **About** dialog.
      placeholder: |
        Example: 4.21
    validations:
      required: false

  - type: input
    id: android-version
    attributes:
      label: Android version
      placeholder: |
        Example: 15
    validations:
      required: true


  - type: textarea
    id: detail
    attributes:
      label: The issue
    validations:
      required: true

